server:
  port: 8181
spring:
  application:
    name: reactive-clean-architecture
  r2dbc:
    url: r2dbc:postgresql://localhost:15432/introwebflux
    username: postgres
    password: postgres
    pool:
      enabled: true
      #      validation-query: SELECT 1; # slow performance when enabled
      initial-size: 10 # default value
      max-size: 300 # default value