server:
  port: 8181
spring:
  application:
    name: reactive-clean-architecture
  r2dbc:
    url: r2dbc:postgresql://localhost:15432/introwebflux
    username: postgres
    password: postgres
    pool:
      enabled: true
      #validation-query: SELECT 1; # slow performance when enabled
      initial-size: 10 # default value
      max-size: 300 # default value
debug: false # set as true to see autoconfiguration report
logging:
  pattern:
    console: "[%date{YYYY/MM/dd HH:mm:ss:SSS}] %clr([${PID:- }]){magenta} -- %clr([%level]){green} [%thread] %clr([%logger{10}:%line]){cyan} : %msg%n"
  level:
    org.springframework.data.r2dbc: trace
    #org.springframework.transaction: trace