server:
  port: 8080
  tomcat:
    threads:
      max: 300
spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/introwebflux
    username: postgres
    password: postgres
    hikari:
      driver-class-name: org.postgresql.Driver
      connection-timeout: 30000
      maximum-pool-size: 300
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1;
      validation-timeout: 28000
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
debug: false # set as true to see autoconfiguration report
logging:
  pattern:
    console: "[%date{YYYY/MM/dd HH:mm:ss:SSS}] %clr([${PID:- }]){magenta} -- %clr([%level]){green} [%thread] %clr([%logger{10}:%line]){cyan} : %msg%n"
  level:
    #org.hibernate: trace
    org.hibernate.SQL: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
    #org.springframework.transaction: trace