server:
  port: 8080
  tomcat:
    threads:
      max: 300
spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/introwebflux
    username: postgres
    password: postgres
    hikari:
      driver-class-name: org.postgresql.Driver
      connection-timeout: 30000
      maximum-pool-size: 300
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1;
      validation-timeout: 28000
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
logging:
  level:
#    org.springframework.data: trace
#    org.springframework.transaction: trace
#    org.hibernate: trace
    org.hibernate.SQL: debug